eureka:
  image: "epay-server:1.0.0"
  volumes:
      - /log:/log
  hostname: eureka
  ports:
    - "2000:2000"
  net: "host"

config:
  image: "epay-config:1.0.0"
  volumes:
      - /log:/app/log
  hostname: config
  environment:
     EUREKA_HOST: eureka
     EUREKA_PORT: 2000
  ports:
   - "2020:2020"
  net: "host"

service:
  image: "epay-service:1.0.0"
  volumes:
      - /log:/app/log
  hostname: service
  environment:
     EUREKA_HOST: eureka
     EUREKA_PORT: 2000
     SERVER_PORT: 3000
  ports:
    - "3000:3000"
  net: "host"

web:
  image: "epay-web:1.0.0"
  volumes:
      - /log:/app/log
  hostname: web
  environment:
     EUREKA_HOST: eureka
     EUREKA_PORT: 2000
     SERVER_PORT: 3010
  ports:
    - "3010:3010"
  net: "host"

zuul:
  image: "epay-gateway:1.0.0"
  volumes:
      - /log:/app/log
  hostname: zuul
  environment:
     EUREKA_HOST: eureka
     EUREKA_PORT: 2000
  ports:
    - "3020:3020"
  net: "host"